# label: globs (relative to repo root) that trigger it
"tests":
  - changed-files:
      - any-glob-to-any-file: ['tests/**']

"firmware":
  - changed-files:
      - any-glob-to-any-file: ['firmware/**']

"daqapp":
  - changed-files:
      - any-glob-to-any-file: ['daqapp/**']

"node configs":
  - changed-files:
      - any-glob-to-any-file: ['firmware/can_library/configs/**']

"a_box":
  - changed-files:
      - any-glob-to-any-file: ['firmware/source/a_box/**']

"daq":
  - changed-files:
      - any-glob-to-any-file: ['firmware/source/daq/**']

"dashboard":
  - changed-files:
      - any-glob-to-any-file: ['firmware/source/dashboard/**']

"driveline":
  - changed-files:
      - any-glob-to-any-file: ['firmware/source/driveline/**']

"main_module":
  - changed-files:
      - any-glob-to-any-file: ['firmware/source/main_module/**']

"pdu":
  - changed-files:
      - any-glob-to-any-file: ['firmware/source/pdu/**']


"torque_vector":
  - changed-files:
      - any-glob-to-any-file: ['firmware/source/torque_vector/**']

"phal":
  - changed-files:
      - any-glob-to-any-file: ['firmware/common/phal*/**']

"common":
  - changed-files:
      - any-glob-to-any-file: ['firmware/common/**']

"ci/cd":
  - changed-files:
      - any-glob-to-any-file: ['.github/**']

"docs":
  - changed-files:
      - any-glob-to-any-file: ['docs/**']

"vscode":
  - changed-files:
      - any-glob-to-any-file: ['.vscode/**']