var searchData=
[
  ['scan_2eh_0',['SCAN.h',['../SCAN_8h.html',1,'']]],
  ['sd_5fcard_2ec_1',['sd_card.c',['../sd__card_8c.html',1,'']]],
  ['sd_5fcard_2eh_2',['sd_card.h',['../sd__card_8h.html',1,'']]],
  ['sd_5ffsm_2edrawio_2epng_3',['SD_FSM.drawio.png',['../SD__FSM_8drawio_8png.html',1,'']]],
  ['sdc_2ec_4',['sdc.c',['../sdc_8c.html',1,'']]],
  ['sdc_2eh_5',['sdc.h',['../sdc_8h.html',1,'']]],
  ['sdio_2ec_6',['sdio.c',['../sdio_8c.html',1,'']]],
  ['sdio_2eh_7',['sdio.h',['../sdio_8h.html',1,'']]],
  ['sensors_2eh_8',['sensors.h',['../sensors_8h.html',1,'']]],
  ['setup_2emd_9',['setup.md',['../setup_8md.html',1,'']]],
  ['spi_2ec_10',['spi.c',['../phal__F4_2spi_2spi_8c.html',1,'(Global Namespace)'],['../phal__G4_2spi_2spi_8c.html',1,'(Global Namespace)']]],
  ['spi_2eh_11',['spi.h',['../phal__F4_2spi_2spi_8h.html',1,'(Global Namespace)'],['../phal__G4_2spi_2spi_8h.html',1,'(Global Namespace)']]],
  ['spi_5fpriv_2ec_12',['spi_priv.c',['../spi__priv_8c.html',1,'']]],
  ['spi_5fpriv_2eh_13',['spi_priv.h',['../spi__priv_8h.html',1,'']]],
  ['spi_5ftest_2ec_14',['spi_test.c',['../spi__test_8c.html',1,'']]],
  ['spmc_2ec_15',['spmc.c',['../spmc_8c.html',1,'']]],
  ['spmc_2eh_16',['spmc.h',['../spmc_8h.html',1,'']]],
  ['stale_5fdetection_2edrawio_2epng_17',['stale_detection.drawio.png',['../stale__detection_8drawio_8png.html',1,'']]],
  ['state_2ec_18',['state.c',['../state_8c.html',1,'']]],
  ['state_2eh_19',['state.h',['../state_8h.html',1,'']]],
  ['strbuf_2ec_20',['strbuf.c',['../strbuf_8c.html',1,'']]],
  ['strbuf_2eh_21',['strbuf.h',['../strbuf_8h.html',1,'']]],
  ['strbuf_5ftest_2ecpp_22',['strbuf_test.cpp',['../strbuf__test_8cpp.html',1,'']]],
  ['switches_2ec_23',['switches.c',['../switches_8c.html',1,'']]],
  ['switches_2eh_24',['switches.h',['../switches_8h.html',1,'']]],
  ['syscalls_2ec_25',['syscalls.c',['../syscalls_8c.html',1,'']]],
  ['syscalls_2eh_26',['syscalls.h',['../syscalls_8h.html',1,'']]]
];
