[workspace]
resolver = "3"
members = [
    "daqapp",
    "daqcore",
    "daqcli",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
daqcore = { path = "daqcore" }

can_decode = "0.7.2"
chrono = "0.4.44"
log = "0.4.29"
bytemuck = { version = "1.25.0", features = ["derive"] }
csv = "1.4.0"