name: Build DAQApp

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    container:
      image: irvingywang/per-firmware:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cargo Format
        working-directory: daqapp
        run: cargo fmt --all --check

  build:
    name: Build DAQApp
    runs-on: ubuntu-latest
    container:
      image: irvingywang/per-firmware:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cache Cargo
        uses: actions/cache@v6
        with:
          path: |
            /opt/cargo/registry
            /opt/cargo/git
            daqapp/target
          key: ${{ runner.os }}-daqapp-${{ hashFiles('daqapp/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-daqapp-

      - name: Build DAQ app
        working-directory: daqapp
        run: cargo build --all-targets

      - name: Show compiler warnings
        working-directory: daqapp
        run: |
          echo "Compiler warnings:"
          cargo check --all-targets --message-format short
        continue-on-error: true
