name: Build DAQ Workspace

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    container:
      image: irvingywang/per-firmware:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cargo Format
        working-directory: daq
        run: cargo fmt --all --check

  build:
    name: Build DAQ Workspace
    runs-on: ubuntu-latest
    container:
      image: irvingywang/per-firmware:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cache Cargo
        uses: actions/cache@v6
        with:
          path: |
            /opt/cargo/registry
            /opt/cargo/git
            daq/target
          key: ${{ runner.os }}-daq-${{ hashFiles('daq/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-daq-

      - name: Build DAQ workspace
        working-directory: daq
        run: cargo build --workspace --all-targets --locked

      - name: Show compiler warnings
        working-directory: daq
        run: |
          echo "Compiler warnings:"
          cargo check --workspace --all-targets --locked --message-format short
        continue-on-error: true
