name: Static Analysis

on:
    pull_request:
    push:
        branches: [master]

permissions:
    contents: read

jobs:
    cppcheck:
        name: cppcheck
        runs-on: ubuntu-latest
        container:
            image: irvingywang/per-firmware:latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Fix git ownership
              run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - name: Install cppcheck
              run: apt-get update && apt-get install -y cppcheck

            - name: Run cppcheck
              run: python3 per_build.py firmware --check
              